# **HWK2: Text Processing, Classification and Topic Modeling Assignment**
# Aditya Sahu
# CMPE 297

In [1]:
# importing required libraries
import re
import nltk
from nltk.corpus import movie_reviews
import string
import pandas as pd
from nltk.corpus import stopwords

nltk.download('movie_reviews')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')

[nltk_data] Downloading package movie_reviews to /root/nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [2]:
from numpy import zeros
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [3]:
docs = [movie_reviews.raw(i) for i in movie_reviews.fileids()]
docs[0]

'plot : two teen couples go to a church party , drink and then drive . \nthey get into an accident . \none of the guys dies , but his girlfriend continues to see him in her life , and has nightmares . \nwhat\'s the deal ? \nwatch the movie and " sorta " find out . . . \ncritique : a mind-fuck movie for the teen generation that touches on a very cool idea , but presents it in a very bad package . \nwhich is what makes this review an even harder one to write , since i generally applaud films which attempt to break the mold , mess with your head and such ( lost highway & memento ) , but there are good and bad ways of making all types of films , and these folks just didn\'t snag this one correctly . \nthey seem to have taken this pretty neat concept , but executed it terribly . \nso what are the problems with the movie ? \nwell , its main problem is that it\'s simply too jumbled . \nit starts off " normal " but then downshifts into this " fantasy " world in which you , as an audience membe

1. Create a bag of words representation of the movie review data from the Text Mining Assignment 
- Use sklearn's CountVectorizer for the bag of words representation
- Create versions of the data using unigrams and also bigrams (ngram_range parameter in CountVectorizer allows you to specify what ngrams to use)

In [4]:
vectorizer = CountVectorizer(stop_words='english')
unigrams = vectorizer.fit_transform(docs)
print("First 50 unigrams are:")
print(vectorizer.get_feature_names_out()[:50])
print("\nUnigram Bag of Words Representation:")
print(unigrams.toarray())
print("\nUnigram Shape:", unigrams.shape)


First 50 unigrams are:
['00' '000' '0009f' '007' '00s' '03' '04' '05' '05425' '10' '100' '1000'
 '10000' '100m' '101' '102' '103' '104' '105' '106' '107' '108' '109'
 '10b' '10s' '10th' '11' '110' '111' '112' '113' '1138' '114' '115' '117'
 '118' '11th' '12' '121' '122' '123' '125' '126' '127' '1272' '128' '129'
 '1298' '12th' '13']

Unigram Bag of Words Representation:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Unigram Shape: (2000, 39354)


In [5]:
vectorizer2 = CountVectorizer(stop_words='english',ngram_range=(2, 2))
bigrams = vectorizer2.fit_transform(docs)
print("First 50 bigrams are:")
print(vectorizer2.get_feature_names_out()[:50])
print("\nBigram Bag of Words Representation:")
print(bigrams.toarray())
print("\nBigram Shape:", bigrams.shape)


First 50 bigrams are:
['00 cable' '00 feet' '00 like' '00 reviews' '00 showing' '00 strong'
 '00 sunday' '00 task' '00 wasn' '000 000' '000 acre' '000 bail'
 '000 bank' '000 bloodsuckers' '000 budget' '000 cameras' '000 cash'
 '000 clock' '000 copies' '000 cosby' '000 days' '000 dialogue'
 '000 dollars' '000 earthlings' '000 easy' '000 employees' '000 epic'
 '000 everybody' '000 ex' '000 feet' '000 foot' '000 force' '000 gibson'
 '000 gone' '000 grant' '000 guests' '000 haul' '000 helping'
 '000 immerses' '000 instead' '000 just' '000 kind' '000 lb' '000 leagues'
 '000 like' '000 ll' '000 longer' '000 marks' '000 maybe' '000 men']

Bigram Bag of Words Representation:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Bigram Shape: (2000, 494333)


2. Create a tf-idf representation of the same movie review data from the (e.g., using sklearn's TfidfVectorizer)
- Create versions of the data using unigrams and also bigrams (ngram_range parameter in TfidfVectorizer allows you to specify what ngrams to use)

In [6]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
tfidf_unigrams = tfidf_vectorizer.fit_transform(docs)
print("First 50 unigrams are:")
print(tfidf_vectorizer.get_feature_names_out()[:50])
print("\nUnigram Bag of Words Representation:")
print(tfidf_unigrams.toarray())
print("\nUnigram Shape:", tfidf_unigrams.shape)


First 50 unigrams are:
['00' '000' '0009f' '007' '00s' '03' '04' '05' '05425' '10' '100' '1000'
 '10000' '100m' '101' '102' '103' '104' '105' '106' '107' '108' '109'
 '10b' '10s' '10th' '11' '110' '111' '112' '113' '1138' '114' '115' '117'
 '118' '11th' '12' '121' '122' '123' '125' '126' '127' '1272' '128' '129'
 '1298' '12th' '13']

Unigram Bag of Words Representation:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Unigram Shape: (2000, 39354)


In [7]:
tfidf_vectorizer2 = TfidfVectorizer(stop_words='english',ngram_range=(2, 2))
tfidf_bigrams = tfidf_vectorizer2.fit_transform(docs)
print("First 50 bigrams are:")
print(tfidf_vectorizer2.get_feature_names_out()[:50])
print("\nBigram Bag of Words Representation:")
print(tfidf_bigrams.toarray())
print("\nBigram Shape:", tfidf_bigrams.shape)


First 50 bigrams are:
['00 cable' '00 feet' '00 like' '00 reviews' '00 showing' '00 strong'
 '00 sunday' '00 task' '00 wasn' '000 000' '000 acre' '000 bail'
 '000 bank' '000 bloodsuckers' '000 budget' '000 cameras' '000 cash'
 '000 clock' '000 copies' '000 cosby' '000 days' '000 dialogue'
 '000 dollars' '000 earthlings' '000 easy' '000 employees' '000 epic'
 '000 everybody' '000 ex' '000 feet' '000 foot' '000 force' '000 gibson'
 '000 gone' '000 grant' '000 guests' '000 haul' '000 helping'
 '000 immerses' '000 instead' '000 just' '000 kind' '000 lb' '000 leagues'
 '000 like' '000 ll' '000 longer' '000 marks' '000 maybe' '000 men']

Bigram Bag of Words Representation:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Bigram Shape: (2000, 494333)


3. Use Bayesian classification to classify reviews into positive and negative using both the unigram and bigram versions of the bag of words and tf-idf representations from 1 and 2 above (e.g., using sklearn's MultinomialNB or nltk's NaiveBayesClassifier)

In [8]:
movie_reviews.categories()

['neg', 'pos']

We can see that, our movie review dataset has 2 target category, Negative and Positive.

In [9]:
neg = movie_reviews.fileids('neg')
pos = movie_reviews.fileids('pos')
neg_reviews = [movie_reviews.raw(fileids=[i]) for i in neg]
pos_reviews = [movie_reviews.raw(fileids=[i]) for i in pos]
labels = [0] * len(neg_reviews) + [1] * len(pos_reviews)
train_data, test_data, train_labels, test_labels = train_test_split(docs, labels, test_size=0.2)

 Bayesian classification using CountVectorizer




In [10]:
train_unigrams = vectorizer.fit_transform(train_data)
test_unigrams = vectorizer.transform(test_data)
unigramNB = MultinomialNB()
unigramNB.fit(train_unigrams, train_labels)
unigram_pred = unigramNB.predict(test_unigrams)
unigram_acc = accuracy_score(test_labels, unigram_pred)
print("Unigram bag of words accuracy using CountVectorizer :", unigram_acc)
train_bigrams = vectorizer2.fit_transform(train_data)
test_bigrams = vectorizer2.transform(test_data)
bigramNB = MultinomialNB()
bigramNB.fit(train_bigrams, train_labels)
bigram_pred = bigramNB.predict(test_bigrams)
bigram_acc = accuracy_score(test_labels, bigram_pred)
print("Bigram bag of words accuracy usnig CountVectorizer:", bigram_acc)

Unigram bag of words accuracy using CountVectorizer : 0.8
Bigram bag of words accuracy usnig CountVectorizer: 0.7625


 Bayesian classification using TF-IDF


In [11]:
train_tfidf_unigrams = tfidf_vectorizer.fit_transform(train_data)
test_tfidf_unigrams = tfidf_vectorizer.transform(test_data)
tfidf_unigramNB = MultinomialNB()
tfidf_unigramNB.fit(train_tfidf_unigrams, train_labels)
tfidf_unigram_pred = tfidf_unigramNB.predict(test_tfidf_unigrams)
tfidf_unigram_acc = accuracy_score(test_labels, tfidf_unigram_pred)
print("Unigram bag of words accuracy using TFIDF :", tfidf_unigram_acc)
tfidf_train_bigrams = tfidf_vectorizer2.fit_transform(train_data)
tfidf_test_bigrams = tfidf_vectorizer2.transform(test_data)
tfidf_bigramNB = MultinomialNB()
tfidf_bigramNB.fit(tfidf_train_bigrams, train_labels)
tfidf_bigram_pred = tfidf_bigramNB.predict(tfidf_test_bigrams)
tfidf_bigram_acc = accuracy_score(test_labels, tfidf_bigram_pred)
print("Bigram bag of words accuracy usnig TFIDF:", tfidf_bigram_acc)

Unigram bag of words accuracy using TFIDF : 0.815
Bigram bag of words accuracy usnig TFIDF: 0.75


4. Use nltk.collocations functions to calculate the top 10 bigram collocations based on PPMI

In [12]:
from nltk.collocations import *
bigram_measures = nltk.collocations.BigramAssocMeasures()
tokenized_docs=[nltk.word_tokenize(i) for i in docs]
finder = BigramCollocationFinder.from_documents(tokenized_docs)
top_10=finder.nbest(bigram_measures.pmi, 10)

In [13]:
top_10[0:10]

[("'92/early", "'93"),
 ("'baby", 'genuises'),
 ("'chateau", 'neuve'),
 ("'five", 'schillings'),
 ("'freaky", 'deaky'),
 ("'hot", 'totty'),
 ("'number", 'cruncher'),
 ('-agent', 'swanbeck'),
 ('05425', 'keywords'),
 ('12-minute', 'uninterrupted')]

5. Topic modeling exercise

Using the example notebook attached to this assignment, create a visualization of scikit-learn's 20newsgroups dataset, but only using articles in the categories 'sci.med', 'sci.space', 'talk.politics.guns'.  Feel free to apply additional pre-processing beyond the one in the example, and to set n_components to different values.

In [14]:
!pip install pyLDAvis 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [15]:
from __future__ import print_function
import pyLDAvis

import pyLDAvis.sklearn
pyLDAvis.enable_notebook()
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
# Load 20 newsgroups dataset
# First, the 20 newsgroups dataset available in sklearn is loaded. As always, the headers, footers and quotes are removed.

We are given catergories 'sci.med', 'sci.space', 'talk.politics.guns'.

In [16]:
cat=[ 'sci.med', 'sci.space', 'talk.politics.guns']
newsgroups = fetch_20newsgroups(subset='all', categories= cat, remove=('headers', 'footers', 'quotes'))
docs_raw = newsgroups.data
print(len(docs_raw))

2887


In [17]:
from pprint import pprint
pprint(list(newsgroups.target_names))

['sci.med', 'sci.space', 'talk.politics.guns']


In [18]:
# Convert to document-term matrix
# Next, the raw documents are converted into document-term matrix, possibly as raw counts or in TF-IDF form.

tf_vectorizer = CountVectorizer(strip_accents = 'unicode',
                                stop_words = 'english',
                                lowercase = True,
                                token_pattern = r'\b[a-zA-Z]{3,}\b',
                                max_df = 0.5, 
                                min_df = 10)
dtm_tf = tf_vectorizer.fit_transform(docs_raw)
print(dtm_tf.shape)

(2887, 3774)


In [19]:
tfidf_vectorizer = TfidfVectorizer(**tf_vectorizer.get_params())
dtm_tfidf = tfidf_vectorizer.fit_transform(docs_raw)
print(dtm_tfidf.shape)

/usr/local/lib/python3.8/dist-packages/sklearn/feature_extraction/text.py:2029: UserWarning: Only (<class 'numpy.float64'>, <class 'numpy.float32'>, <class 'numpy.float16'>) 'dtype' should be used. <class 'numpy.int64'> 'dtype' will be converted to np.float64.
  warnings.warn(


(2887, 3774)


In [20]:
# Fit Latent Dirichlet Allocation models - this step takes a while!

# for TF DTM
lda_tf = LatentDirichletAllocation(n_components=20, random_state=0)
lda_tf.fit(dtm_tf)

# for TFIDF DTM
lda_tfidf = LatentDirichletAllocation(n_components=20, random_state=0)
lda_tfidf.fit(dtm_tfidf)
LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='online', learning_offset=10.0,
             max_doc_update_iter=100, max_iter=10, mean_change_tol=0.001,
             n_jobs=1, n_components=20, perp_tol=0.1, random_state=0,
             topic_word_prior=None, total_samples=1000000.0, verbose=0)


LatentDirichletAllocation(learning_method='online', n_components=20, n_jobs=1,
                          random_state=0)

In [21]:
# Visualizing the models with pyLDAvis, using the term frequency (tf) vectors
pyLDAvis.sklearn.prepare(lda_tf, dtm_tf, tf_vectorizer)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.8/dist-packages/pyLDAvis/_prepare.py:243: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  default_term_info = default_term_info.sort_values(


PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic                                                
13     0.023900  0.095601       1        1  12.353453
9      0.187919 -0.044651       2        1   9.165407
0      0.197029 -0.035090       3        1   8.110006
6     -0.188074  0.012828       4        1   7.566154
19     0.085109 -0.099734       5        1   7.110383
14     0.115642 -0.000777       6        1   6.091422
18    -0.102208  0.236553       7        1   5.797368
8      0.053423 -0.017007       8        1   5.059840
16    -0.214153 -0.147163       9        1   4.721170
12     0.117596  0.040387      10        1   4.679070
15    -0.169022 -0.121706      11        1   4.182410
10     0.123258  0.090283      12        1   4.142263
17    -0.186066 -0.009052      13        1   3.795271
11    -0.125332 -0.140279      14        1   3.677488
3     -0.101508  0.260429      15        1   3.448035
2      0.064975 -0.071254      16        1   2.629294
7      0.170394 -0.084804      17        1   2.373876
5      0.035613  0.083490      18        1   2.276838
1     -0.142965 -0.035590      19        1   1.447100
4      0.054470 -0.012465      20        1   1.373150, topic_info=          Term         Freq        Total Category  logprob  loglift
3176     space  1287.000000  1287.000000  Default  30.0000  30.0000
1485       gun   786.000000   786.000000  Default  29.0000  29.0000
1059       edu   731.000000   731.000000  Default  28.0000  28.0000
471     cancer   310.000000   310.000000  Default  27.0000  27.0000
2202      nasa   494.000000   494.000000  Default  26.0000  26.0000
...        ...          ...          ...      ...      ...      ...
3433     texas    12.122145   100.540628  Topic20  -5.4300   2.1725
188       area    12.603350   159.049444  Topic20  -5.3911   1.7528
3685       way    12.751350   470.730418  Topic20  -5.3794   0.6794
189      areas    11.857694    97.528103  Topic20  -5.4520   2.1809
2550  possible    11.925443   250.757765  Topic20  -5.4463   1.2422

[1182 rows x 6 columns], token_table=      Topic      Freq      Term
term                           
1         1  0.982563   abiding
5         4  0.073267  absolute
5         6  0.146533  absolute
5        16  0.512866  absolute
5        17  0.146533  absolute
...     ...       ...       ...
3764     19  0.011532     years
3765     10  0.123419     yeast
3765     12  0.875151     yeast
3768      7  0.034395    yogurt
3768     12  0.928670    yogurt

[5473 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[14, 10, 1, 7, 20, 15, 19, 9, 17, 13, 16, 11, 18, 12, 4, 3, 8, 6, 2, 5])

In [22]:
# Visualizing the models with pyLDAvis, using the tf-idf vectors

pyLDAvis.sklearn.prepare(lda_tfidf, dtm_tfidf, tfidf_vectorizer)


/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.8/dist-packages/pyLDAvis/_prepare.py:243: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  default_term_info = default_term_info.sort_values(


PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic                                                
19    -0.279771 -0.037280       1        1  43.609010
8     -0.064465  0.012824       2        1  12.473512
2     -0.017458  0.283500       3        1   6.929196
12     0.154810 -0.014537       4        1   5.292081
0      0.069721  0.089482       5        1   5.206922
5      0.132063 -0.060509       6        1   4.116265
9      0.034780  0.049366       7        1   2.683877
6      0.019696 -0.056906       8        1   2.641747
15     0.031715 -0.052090       9        1   2.333530
17     0.022615 -0.044365      10        1   2.010701
18    -0.014971 -0.037036      11        1   1.963468
10     0.006545 -0.030578      12        1   1.521461
7     -0.030352 -0.007443      13        1   1.328149
11     0.000522 -0.017152      14        1   1.277573
14    -0.009256 -0.010781      15        1   1.175582
13    -0.008688 -0.019248      16        1   1.170195
16    -0.007222 -0.013713      17        1   1.151676
3     -0.003784 -0.009926      18        1   1.115090
1     -0.017587 -0.009991      19        1   1.022695
4     -0.018911 -0.013618      20        1   0.977270, topic_info=          Term       Freq      Total Category  logprob  loglift
1059       edu  29.000000  29.000000  Default  30.0000  30.0000
1485       gun  30.000000  30.000000  Default  29.0000  29.0000
3176     space  42.000000  42.000000  Default  28.0000  28.0000
613        com  19.000000  19.000000  Default  27.0000  27.0000
3160      soon  13.000000  13.000000  Default  26.0000  26.0000
...        ...        ...        ...      ...      ...      ...
190       aren   0.536069   8.432887  Topic20  -5.6028   1.8725
1244       fat   0.355912   6.875835  Topic20  -6.0124   1.6671
2717     quite   0.385625  15.073828  Topic20  -5.9322   0.9623
2887  response   0.342014   7.336639  Topic20  -6.0522   1.5624
1771       isn   0.341072  15.019528  Topic20  -6.0550   0.8431

[962 rows x 6 columns], token_table=      Topic      Freq     Term
term                          
4         8  0.663673  absence
8         6  0.492852   absurd
9         3  0.687500    abuse
30        6  0.518751    acids
33        5  0.711607    acted
...     ...       ...      ...
3765     12  0.963982    yeast
3766      1  0.682021      yes
3766      2  0.151560      yes
3766     19  0.075780      yes
3768     12  0.721908   yogurt

[1435 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[20, 9, 3, 13, 1, 6, 10, 7, 16, 18, 19, 11, 8, 12, 15, 14, 17, 4, 2, 5])